name: Multi-Job Workflow

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:

        - name: Build Code
          run: echo "Building the Code"
    
    test:
        runs-on: ubuntu-latest
        needs: [build]
        steps:

        - name: Test Code
          run: echo "Testing the Code"
    
    deploy:
        runs-on: ubuntu-latest
        needs: [test]
        steps:

        - name: Deploy Code
          run: echo "Deploying the Code"