name: Path Ignore

on:
    push:
        paths-ignore:
          - '*.md'
          - 'docs/**'

        branches:
            - main
            - release/*

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Print
            run: echo "ignore path"